config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  # get "/" => "home#index", as: "home"
  get "/medical" => "home#medical"
  get "/about" ,:to => "home#about"
  get "/contact" => "home#contact"
  get "/videos" => "home#videos"
  get "/video1" => "home#video1"
  get "/video2" => "home#video2"
  get "/video3" => "home#video3"
  get "/video4" => "home#video4"
  get "/video5" => "home#video5"
  get "/video6" => "home#video6"
  get "/video7" => "home#video7"

  get "/products/showall" => "products#showall"



  post "/form-response" => "home#email"


  devise_for :users, :controllers => { registrations: 'registrations' }
  #
  resources :products do
    resources :reviews
  end

require 'bootstrap'
require 'sendgrid-ruby'

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews

  has_attached_file :visual, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :visual, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  # before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'sendgrid-ruby'

  skip_before_filter  :verify_authenticity_token

  def index
    # get "home#index"
  end

  def medical
  end

  def about
  end

  def contact



  end

  def email

        # set the from, subject and to addresses
        from = SendGrid::Email.new(email: params[:from])
        subject = params[:subject]
        to = SendGrid::Email.new(email: "martoranov94@gmail.com")


          # set the content to send in the email
          content = SendGrid::Content.new(type: 'text/plain', value: params[:content])

          # set the mail attribute values
          mail = SendGrid::Mail.new(from, subject, to, content)

          # pass in the sendgrid api key
          sg = SendGrid::API.new(api_key: ENV["SENDGRID_API_KEY"])

          # send the email
          response = sg.client.mail._('send').post(request_body: mail.to_json)

          # display the response status code and body
          puts "Status code = #{response.status_code}"
          puts response.body

          redirect_to contact_path

  end


  def video1
  end

  def video2
  end

  def video3
  end

  def video4
  end

  def video5
  end

 def video6
 end

def video7
end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)

    if @product.save
      flash[:notice] = "Product successfully created"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated."
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Product successfully deleted."
      redirect_to products_path
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def showall
    @products = Product.all
    render json: @products
  end

  private

  def product_params
    params.require(:product).permit(:name, :thc_content, :about, :uses, :effect, :visual, :variety)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    @user = User.new
  end

  private

 def sign_up_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :city, :state, :zip_code)
 end

 def account_update_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :city, :state, :zip_code)
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.product_id = params[:product_id]
    @review.user_id = current_user.id

    puts params.inspect

    if @review.save
      flash[:notice] = "Review sumbitted."
      redirect_to product_path(params[:product_id])
    else
      flash[:alert] = "There was a problem adding your review, please try again."
      redirect_to new_product_review_path
    end
  end


    def show
      @review = Review.find(params[:id])
      @product = Product.find(params[:product_id])
    end

  def edit
    @review = Review.find(params[:id])
    @product = Product.find(params[:product_id])
    @user = @review.user_id


  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Your review has been updated"
      redirect_to product_review_path
    else
      flash[:alert] = "There was a problem updating your review."
      redirect_to edit_product_review_path(@review)
    end

  end


  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:notice] = "Your review has been deleted."
      redirect_to product_path(params[:product_id])
    else
      flash[:alert] = "Your review could not be deleted."
      redirect_to edit_product_review_path(@review)
    end
  end

  private


  def review_params
    params.require(:review).permit(:content, :used_for)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/about.html.erb
<h2 class="about-h2">About Highline</h2>

<div class="about-box about-1">
  <%= image_tag("leaf.png", class: "about-pic-1") %>

  <p class="about-text" id="about-text-1">Highline offers information the best marijuana products available in New York City. Through the many uses of this wonderful plant, Highline provides exactly what you need. Whether it's for medicinal, recreational, or other practical uses, you will be provided with a plethora of highly accurate and useful information. By setting the highest standards in the weed business, we are way ahead of the competition. Whether you’re new to cannabis, a medical marijuana patient, or a seasoned consumer, Highline is the perfect destination for you.</p>

</div>

<div class="about-box about-2">

  <p class="about-text" id="about-text-2">While Highline serves as a top information hub of marijuana, knowing New York City's legislation is very important. Possession of 25 grams or less of marijuana is punishable by a fine of $100 for the first offense. For the second offense, the penalty increases to a $200 fine and for subsequent offenses the fine increases to $250 and a maximum of 15 days in jail time may be imposed. A third offense is a potential misdemeanor of up to 5 days jail time and/or fine up to $250. Jail time and fines increase in tandem with the amount possessed. </p>

  <%= image_tag("high_line_day.jpg", class: "about-pic-2") %>

</div>

app/views/home/contact.html.erb
<div class="bg">
  <div id="form-div">

    <div class="contact_form">
      <h2 class="learn_more">Want to Learn More?</h1>
      <p class="contact_us" >Contact Us</p>
    </div>

    <form action="/form-response" method ="post">
      <input class="email-input" type="text" name="from" value="" placeholder="From:">
      <input class="email-input" type="text" name="subject" value="" placeholder="Subject">
      <br>
      <br>
      <textarea id="content-input" type="text" name="content" value="" placeholder="Type message here" rows="8" cols="70"></textarea>
      <br>
      <br>
      <input class="form-button" id="submit-button" type="submit">
    </form>

  </div>

</div>

app/views/home/index.html.erb
<!-- <div id="statue">
   <h1 id="home-header-1">
    <%= image_tag("statue-2.png", :size => "60x120") %>HIgHLINE
  </h1>
</div> -->


<div class="slideshow">

  <div class="gallery-container">
    <ul id="slides">
      <li id="leaves" class="slide showing"><div id="statue">
        <h1 id="home-header">
          <%= image_tag("statue-2.png", :size => "60x120", :class => "statue") %>HIgHLINE
        </h1>
      </div></li>
      <li id="tasman" class="slide"><div id="statue">
        <h1 id="home-header">
          <%= image_tag("statue-2.png", :size => "60x120", :class => "statue") %>HIgHLINE
        </h1>
      </div></li>
      <li id="greenhouse" class="slide"><div id="statue">
        <h1 id="home-header">
          <%= image_tag("statue-2.png", :size => "60x120", :class => "statue") %>HIgHLINE
        </h1>
      </div></li>
      <li id="joint" class="slide"><div id="statue">
        <h1 id="home-header">
          <%= image_tag("statue-2.png", :size => "60x120", :class => "statue") %>HIgHLINE
        </h1>
      </div></li>
      <li id="brownie" class="slide"><div id="statue">
        <h1 id="home-header">
          <%= image_tag("statue-2.png", :size => "60x120", :class => "statue") %>HIgHLINE
        </h1>
      </div></li>
      <li id="shatter" class="slide"><div id="statue">
        <h1 id="home-header">
          <%= image_tag("statue-2.png", :size => "60x120", :class => "statue") %>HIgHLINE
        </h1>
      </div></li>
    </ul>
  </div>

  <center><div class="gallery-buttons">
      <button class="controls" id="previous">&lt;</button>
      <button class="controls" id="pause">&#10074;&#10074;</button>
      <button class="controls" id="next">&gt;</button>
  </div></center>

</div>

<script type="text/coffeescript" src="home.js"></script>

app/views/home/medical.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Latest Research</title>
  </head>
  <body>

  <div class="giant_div">


<div class= "article">

  <div class= "article_header">
  <center><p class= "main_header">ScienceDaily</p></center>
  <p class= "heading">Cannabis: Non-addictive pathway to pain relief?
  Medicinal properties of cannabis examined</p>
  </div>

<%= image_tag("170112130145_1_540x360.jpg", class: "pict") %>

<div class="content_text">

  <p>Susan Ingram, Ph.D., an associate professor of neurosurgery in the OHSU School of Medicine, is the senior author of new OHSU research that suggests an avenue for developing treatments for chronic pain that harness the medicinal properties of cannabis while minimizing the threat of addiction, January 10, 2017.
  Credit: OHSU/Kristyna Wentz-Graff</p>

  <p>
    Date: January 12, 2017
    Source:Oregon Health and Science University
    Summary: New research suggests an avenue for developing treatments for chronic pain that harness the medicinal properties of cannabis while minimizing the threat of addiction. Therapeutics that target the endocannabinoid system might produce pain relief with fewer side effects compared with opioids.</p>

  <p>OHSU research suggests an avenue for developing treatments for chronic pain that harness the medicinal properties of cannabis while minimizing the threat of addiction.

  The study, conducted in a rodent model, provides additional rationale for the development of therapeutics using cannabinoid receptors to treat chronic pain, which afflicts about 30 percent of the U.S. population. OHSU investigators studied the function of two forms of cell membrane receptors that bind cannabinoids that occur naturally within the body, called endocannabinoids.

  "It may be an avenue where we can get better pain medications that are not addictive," said senior author Susan Ingram, Ph.D., an associate professor of neurosurgery in the OHSU School of Medicine.

  Ingram and colleagues report the treatment of chronic pain has challenged the medical system, with medications that are ineffective or create serious side effects: "However, emerging data indicate that drugs that target the endocannabinoid system might produce analgesia with fewer side effects compared with opioids."

  The body's endocannabinoid system comprises receptors, endocannabinoid molecules and enzymes that make and degrade the endocannabinoids located in the brain and throughout the central and peripheral nervous system. The research team focused on two cannabinoid receptors, known as CB1 and CB2, in the rostral ventromedial medulla -- a group of neurons located in the brainstem known to modulate pain. The study is the first to examine CB1 and CB2 receptor function at the membrane level in late adolescent and adult neurons.

  The researchers observed that chronic inflammatory pain increased activity of CB2 receptors and decreased CB1 activity. Cannabis activates both CB1 and CB2 receptors equally. The study suggests that selective activation of CB2 receptors contributes to the medicinal benefit of cannabis while minimizing the propensity of the other cannabinoid receptor, CB1, to induce tolerance and withdrawal. Ingram said the next phase of the research will further explore this area of brain circuitry, which ultimately could lead to the development of a new class of pain medications.

  Co-authors include lead author Ming-Hua Li, Ph.D., and Katherine L. Suchland, both with the Department of Neurological Surgery, OHSU School of Medicine.

  The study was funded by grants from the National Institutes of Health (DA035316 and R56NS093894) and American Heart Association (13SDG14590005, MH.L.).

  Story Source:

  Materials provided by Oregon Health and Science University. Note: Content may be edited for style and length.

  Journal Reference:

  M.-H. Li, K. L. Suchland, S. L. Ingram. Compensatory activation of cannabinoid CB2 receptor inhibition of GABA release in the rostral ventromedial medulla (RVM) in inflammatory pain. Journal of Neuroscience, 2016; DOI: 10.1523/JNEUROSCI.1310-16.2016
  Cite This Page:
  MLA
  APA
  Chicago
  Oregon Health and Science University. "Cannabis: Non-addictive pathway to pain relief? Medicinal properties of cannabis examined." ScienceDaily. ScienceDaily, 12 January 2017. <www.sciencedaily.com/releases/2017/01/170112130145.htm>.</p>
</div>
</div>

<br>


<hr id="medical-hr">


<br>

      <div class="video">

        <div class="vidheader">
          <center><p class="vidheading">The Scientist (2015) Medical Marijuana: Studying For a Higher Purpose
          - Prof. Dr. Raphael Mechoulam</p></center>
        </div>

          <iframe width="560" height="315" src="https://www.youtube.com/embed/F_YJxzhShNs" frameborder="0" allowfullscreen class ="videolink"></iframe>

          <div class="content_text">

          <p>Published on Nov 30, 2016
          Is weed good for pain? Here’s a study to ponder…
          Medical Marijuana: Low THC Sufficient For Neuropathic Pain
          Caitlyn Fitzpatrick writing in MD reported study results on the analgesic effect of cannabis have been mixed over the years. However, many states allow prescriptions for medical marijuana for a variety of health conditions, including pain. A recent study published in The Journal of Pain looked at the effect of marijuana treatment on neuropathic pain.

          A team of researchers based in California conducted eight-hour human analyses to determine pain level outcomes with the use of vaporized cannabis. The cohort included 42 patients with neuropathic pain related to an injury or disease of the spinal cord. Although most of the participants were also on a traditional treatment, they were still experiencing pain.

          The patients were randomized to take four puffs of vaporized cannabis that contained either placebo, 2.9%, or 6.7% delta 9-tetrahydrocannabinol (THC). Three hours later, the participants took another four to eight puffs – the number of puffs was decided by the patient in order to reduce the placebo effect.
          An 11-point numerical pain intensity rating scale showed that the vaporized cannabis produced a significant analgesic response.

          Two of the highlighted findings included:
          There was significantly more pain relief with active cannabis than placebo.
          The two active doses did not have significantly different outcomes when it came to analgesic potency.
          Comment: Hmmm. Pot appears to work, I guess.
          Category
          Science and Technology
          License
          Standard YouTube License</p>

          </div>

      </div>

      </div>
  </body>
</html>

app/views/home/video1.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Video 1</title>
  </head>
  <body>
    <div class="video1 videos">
        <h3 class="video-h3">The Scientist (2015) Medical Marijuana: Studying For a Higher Purpose
        - Prof. Dr. Raphael Mechoulam</h3>

        <iframe width="560" height="315" src="https://www.youtube.com/embed/fu6FhJIyTEc" frameborder="0" allowfullscreen></iframe>

        <p class="single_blurb">Published on Nov 26, 2015
      “The Scientist” is a documentary that traces the story of Nobel prize nominee Dr. Raphael Mechoulam from his early days as a child of the Holocaust in Bulgaria, through his immigration to Israel, and his career as the chief investigator into the chemistry and biology of the world’s most misunderstood plant. Dr. Mechoulam ascertained that THC interacts with the largest receptor system in the human body, the endocannabinoid system (ECS).
      For further information please visit:
      http://mechoulamthescientist.com/</p>
    </div>
  </body>
</html>

app/views/home/video2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Video 2</title>
  </head>
  <body>

      <div class="video2 videos">
        
        <h3 class= "video-h3">One Of The Best Marijuana Documentary You Will Ever Watch!</h3>

        <iframe width="560" height="315" src="https://www.youtube.com/embed/uEZPsNZwyfo" frameborder="0" allowfullscreen></iframe>

        <p class="single_blurb">Published on Oct 16, 2016
        One Of The Best Marijuana Documentary You Will Ever Watch! Video
        http://www.hemp.gq/one-of-the-best-ma...

        CC License
        Archive https://archive.org

        Producer "Onderkoffer"
        Best Marijuana Documentary You Will Ever Watch! [ Video] : onderkoffer
        Category
        People and Blogs
        License
        Standard YouTube License
        Music
        "Willie The Weeper" by Grand Dominion Jazz Band Listen ad-free with YouTube Red</p>

      </div>

  </body>
</html>

app/views/home/video3.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Video 3</title>
  </head>
  <body>

      <div class="video3 videos">
        <h3 class="video-h3">Cannabis 101: 5 Basic Cannabis Questions Answered</h3>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/h7pg5Vbuj10" frameborder="0" allowfullscreen></iframe>
        <p class="single_blurb">Published on Jun 2, 2015
        https://www.leafly.com/

        In this week's episode of Leafly's Cannabis 101 we answer 5 basic cannabis questions we receive all the time. Watch the video to find some quick answers to questions like...
        1. How will cannabis affect me?
        2. What is the difference between medical and recreational cannabis?
        3. How do I find medical or recreational cannabis?
        4. How long does it take for an edible to kick in?
        5. How do I safely store my cannabis?

        For more information on cannabis strains, news, and information visit https://Leafly.com or download the free mobile app for iOS and Andoid.

        Thanks to our friends at The Novel Tree for the location/background.
        </p>



      </div>

  </body>
</html>

app/views/home/video4.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Video 4</title>
  </head>
  <body>

    <div class="video4 videos">
      <h3 class="video-h3">Medical marijuana in Florida: from seed to sale</h3>

      <iframe width="560" height="315" src="https://www.youtube.com/embed/jYGUarbhY5Y" frameborder="0" allowfullscreen></iframe>

      <p class="single_blurb">Published on Jan 6, 2017
      As questions linger on how Florida will regulate the medical marijuana industry, Katie LaGrone takes you behind-the-scenes and beneath the soil to show you how one company is cultivating legal cannabis.

      The ABC Action News app brings you the latest trusted news and information.

      ABC Action News is Taking Action For You with leading local news coverage, "Certified Most Accurate" weather forecasts, and award-winning I-Team investigations.

      ABC Action News, WFTS, covers local news in Tampa Bay and Florida.
      </p>


    </div>
  </body>
</html>

app/views/home/video5.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Video 5</title>
  </head>
  <body>

    <div class="video5 videos">
        <h3 class="video-h3">Right Strain of Medical Marijuana
        Dr. Rachna Patel: The Medical Marijuana Expert</h3>

      <iframe width="560" height="315" src="https://www.youtube.com/embed/A4-jet2OFcc" frameborder="0" allowfullscreen></iframe>

        <p class="single_blurb">Published on Nov 25, 2016
      What’s the right strain of medical marijuana for my medical condition?

      A lot of times I get asked the question, Hey Dr. Patel, what’s the right strain of medical marijuana for my medical condition? And you know what it's a difficult question for me to answer. The reason is that strains are named pretty arbitrarily.

      What do I mean by this?

      Basically, an OG Kush that you buy from one dispensary may not have the same effect as an OG Kush that you buy from another dispensary.

      It's the same even if you go to buy the OG Kush at the same dispensary. The OG Kush that you buy the second time around may not have the same effect as the OG Kush you bought the first time.

      If you're using marijuana for medical reasons, then what you're aiming for are consistent results.

      To get these consistent results, what you really want to be focusing on are the exact amounts of the chemicals in the marijuana. These are chemicals like THC and CBD, for instance.

      I hope you found that little tidbit of information helpful. As always, if you have questions for me, post them in the comments section below. I’ll be more than happy to answer them in the next video.


      My website: http://www.drrachnapatel.com/
      Blog post: http://www.drrachnapatel.com/strains-...

      DISCLAIMER

      The information in this video and on the website (http://www.drrachnapatel.com) is for educational and informational purposes only. It should not take the place of seeing a physician and should not be used to diagnose or treat a health problem or disease. It also does not establish a physician-patient relationship between you and Dr. Patel. Individual results may vary. The information contained in this video and on the website (http://www.drrachnapatel.com) has not been evaluated by the FDA (Food and Drug Administration).</p>


    </div>
  </body>
</html>

app/views/home/video7.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Video 6</title>
  </head>
  <body>
    <div class="video7 videos">
        <h3 class="video-h3">Weed Grandma Shows Us How to 420 Braise It: BONG APPÉTIT</h2>

        <iframe width="560" height="315" src="https://www.youtube.com/embed/Z2Xd7cseGcE" frameborder="0" allowfullscreen></iframe>

        <p class="single_blurb">Published on Dec 10, 2014
        Watch the first episode of SMOKEABLES: How to Make a Gravity Bong - http://bit.ly/28XSWBi

        Recipe: make chicken "pot-cciatore" at home - http://bit.ly/1x2cPfT

        Join our constant high in Bong Appetit, a new show about the wonders of weed-infused drinks and beverages. Throughout the series, we will be introduced to the many uses of marijuana—from curing the body to just smoking it for a good time.

        In our first episode, host Matt Zimbric heads to a secret Californian medical marijuana garden run by Nonna Marijuana, a 91-year-old grandmother who cooks classic Italian with a twist. Using buds grown by her own daughter, Nonna teaches Matt a foolproof method for infusing cannabis into butter, then guides him through preparing Chicken "Pot-cciatore" and gnocchi in ganja butter. Along the way, she explains how and why she recommends medical marijuana to those in need—without ever getting high on her own supply. Matt, on the other hand, may regret going back for seconds.

        Read: 91-Year Old Nonna Marijuana is the Queen of Weed Cuisine - http://bit.ly/1GdiMIp

        Check out 'A Gourmet Weed Dinner At Hunter S. Thompson’s House' - http://bit.ly/1z6FL4v

        Subscribe to Munchies here: http://bit.ly/Subscribe-to-MUNCHIES

        Check out http://munchies.tv for more!

        Follow Munchies here:
        Facebook: http://facebook.com/munchies
        Twitter: http://twitter.com/munchies
        Tumblr: http://munchies.tumblr.com
        Instagram: http://instagram.com/munchiesvice
        Category
        Entertainment
        License
        Standard YouTube License</p>



    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="http://images.clipartpanda.com/weed-leaf-leafcircle.png">
    <link href="https://fonts.googleapis.com/css?family=Megrim|Josefin+Sans" rel="stylesheet">
    <title>Highline</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>

  </head>

  <body>

    <ul class="nav">
      <p class="navbar_text_pull_right">
        <% if user_signed_in? %>

          <span id="right-nav-links">
            <%= link_to "Home", root_path, :class => 'navbar-link' %> |

            <%= link_to "About", about_path, :class => 'navbar-link'  %> |

            <%= link_to "Latest Research", medical_path, :class => 'navbar-link'  %> |

            <%= link_to "Products", products_path,  :class => 'navbar-link'  %> |

            <%= link_to "Videos", videos_path,  :class => 'navbar-link'  %> |

            <%= link_to "Contact", contact_path,  :class => 'navbar-link'  %> |

            <%= link_to "Edit Profile", edit_user_registration_path,  :class => 'navbar-link'  %> |

            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

            |                                 Logged in as <strong><%= current_user.email %></strong>

          <% else %>
            <%= link_to "Home", root_path, :class => 'navbar-link' %> |
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </span>
      </p>
    </ul>


    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <br>
    <br><br><br><br>
    <div class="disclaimer">
      <footer>

        <p>WARNING! THIS IS NOT A REAL WEBSITE. WE ARE NOT SELLING ANYTHING HERE. THIS IS A SCHOOL PROJECT FOR THE NEW YORK CODE AND DESIGN ACADEMY. WE ARE LEARNING HOW TO MAKE WEBSITES AND APPS. THIS WEBSITE IS NOT INTENDED FOR ACTUAL USE, IT IS FOR THE SOLE PURPOSE OF LEARNING HOW TO MAKE WEBSITES AND APPS WITH THE NEW YORK CODE AND DESIGN ACADEMY.</p>

        <p>The information provided on this website is for general information purposes only. While we endeavor to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability or suitability of the information contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.</p>

        <p>In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.</p>

      </footer>
    </div>

      <%= javascript_include_tag 'application'  %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product, :html => { :multipart => true } do |form| %>
  <%= form.file_field :visual %>
  <br>
  <%= form.text_field :name, placeholder: "Product name" %>
  <br>
  <%= form.text_field :variety, placeholder: "Type" %>
  <br>
  <%= form.text_field :thc_content, placeholder: "THC Content" %>
  <br>
  <%= form.text_area :about, placeholder: "About" %>
  <br>
  <%= form.text_area :uses, placeholder: "Uses" %>
  <br>
  <%= form.text_area :effect, placeholder: "Effect" %>
  <br>
  <%= form.submit ("Post") %>
<% end %>

app/views/reviews/edit.html.erb
EDIT REVIEW